import { Anime, UserProfile, WatchHistoryItem } from './types';

// High quality themed anime artwork images for posters & banners
const IMAGES = {
  cyberpunkPoster: '/images/poster-cyberpunk.png',
  cyberpunkBanner: '/images/banner-cyberpunk.png',
  fantasyPoster: '/images/poster-magic.png',
  fantasyBanner: '/images/banner-4.png',
  spacePoster: '/images/poster-space.png',
  spaceBanner: '/images/banner-mecha.png',
  samuraiPoster: '/images/poster-samurai.png',
  samuraiBanner: '/images/banner-1.png',
  mechaPoster: '/images/poster-mecha.png',
  mechaBanner: '/images/banner-mecha.png',
  magicPoster: '/images/poster-magic.png',
  magicBanner: '/images/banner-4.png',
  moviePoster: '/images/poster-space.png',
  movieBanner: '/images/banner-cyberpunk.png',
  sampleVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
};

export const MOCK_GENRES = [
  'Action',
  'Adventure',
  'Cyberpunk',
  'Fantasy',
  'Sci-Fi',
  'Slice of Life',
  'Supernatural',
  'Mecha',
  'Mystery',
  'Romance',
  'Comedy',
  'Drama',
];

export const MOCK_STUDIOS = [
  'Kurogane Animation',
  'Aetherial Works',
  'Nexus Vision',
  'Starlight Paradigm',
  'Mappa Horizon',
  'Kyoto Wave',
];

const generateEpisodes = (count: number, prefix: string) => {
  return Array.from({ length: count }, (_, i) => ({
    id: `ep-${i + 1}`,
    number: i + 1,
    title: `Episode ${i + 1}: ${['The Awakening', 'Shadows of the Past', 'Beyond the Event Horizon', 'Unbroken Vow', 'Echoes in the Dark', 'Convergence', 'The Final Starlight'][i % 7]}`,
    thumbnail: IMAGES.spaceBanner,
    duration: '24m 15s',
    airDate: '2024-04-12',
    description: `The story intensifies as main characters face unforeseen challenges in their journey through ${prefix}. Tactical strategies and emotional revelations unfold.`,
    videoUrl: IMAGES.sampleVideo,
    isFiller: i === 4,
  }));
};

export const MOCK_ANIME: Anime[] = [
  {
    id: '1',
    slug: 'chronicles-of-aetheria',
    title: 'Chronicles of Aetheria',
    japaneseTitle: 'エーテリア戦記',
    synopsis: 'In a neon-drenched metropolis powered by ancient arcane energy, a rogue courier discovers a forbidden memory matrix that could unlock the secrets of the world’s celestial architects or trigger absolute oblivion.',
    posterImage: IMAGES.cyberpunkPoster,
    bannerImage: IMAGES.cyberpunkBanner,
    rating: 9.2,
    scoreCount: 142300,
    rank: 1,
    popularity: 298400,
    format: 'TV',
    status: 'Ongoing',
    episodesCount: 24,
    releasedYear: 2024,
    season: 'Spring',
    studio: 'Aetherial Works',
    genres: ['Action', 'Cyberpunk', 'Sci-Fi', 'Mystery'],
    featured: true,
    trending: true,
    popular: true,
    latest: true,
    episodes: generateEpisodes(24, 'Aetheria'),
  },
  {
    id: '2',
    slug: 'starlight-valkyrie',
    title: 'Starlight Valkyrie: Resonance',
    japaneseTitle: 'スターライトヴァルキリー',
    synopsis: 'When cosmic leviathans threaten planetary outposts, an elite squad of mech pilots syncs their consciousness with celestial armor to fight for humanity’s last sanctuary.',
    posterImage: IMAGES.mechaPoster,
    bannerImage: IMAGES.mechaBanner,
    rating: 8.8,
    scoreCount: 98100,
    rank: 8,
    popularity: 185000,
    format: 'TV',
    status: 'Ongoing',
    episodesCount: 12,
    releasedYear: 2024,
    season: 'Winter',
    studio: 'Nexus Vision',
    genres: ['Mecha', 'Sci-Fi', 'Action'],
    featured: true,
    trending: true,
    popular: true,
    latest: true,
    episodes: generateEpisodes(12, 'Starlight Valkyrie'),
  },
  {
    id: '3',
    slug: 'blade-of-the-eclipse',
    title: 'Blade of the Eclipse',
    japaneseTitle: '日蝕の剣士',
    synopsis: 'A lone swordmaster wandering through shattered kingdoms carries an cursed odachi that devours shadow spirits. To break his curse, he must defeat the seven Lunar Sovereigns.',
    posterImage: IMAGES.samuraiPoster,
    bannerImage: IMAGES.samuraiBanner,
    rating: 9.0,
    scoreCount: 210500,
    rank: 3,
    popularity: 340000,
    format: 'TV',
    status: 'Completed',
    episodesCount: 26,
    releasedYear: 2023,
    season: 'Fall',
    studio: 'Kurogane Animation',
    genres: ['Action', 'Supernatural', 'Fantasy'],
    featured: true,
    trending: true,
    popular: true,
    episodes: generateEpisodes(26, 'Eclipse Blade'),
  },
  {
    id: '4',
    slug: 'astral-alchemist',
    title: 'The Astral Alchemist',
    japaneseTitle: '星詠みの錬金術士',
    synopsis: 'In a floating academy city built atop ancient star runes, a prodigy student accidentally transmutes a sentient starlight entity, sparking a race against rogue inquisitors.',
    posterImage: IMAGES.magicPoster,
    bannerImage: IMAGES.magicBanner,
    rating: 8.6,
    scoreCount: 75400,
    rank: 15,
    popularity: 132000,
    format: 'TV',
    status: 'Ongoing',
    episodesCount: 12,
    releasedYear: 2024,
    season: 'Spring',
    studio: 'Starlight Paradigm',
    genres: ['Fantasy', 'Adventure', 'Slice of Life'],
    featured: false,
    trending: true,
    popular: false,
    latest: true,
    episodes: generateEpisodes(12, 'Astral Alchemist'),
  },
  {
    id: '5',
    slug: 'beyond-the-event-horizon-movie',
    title: 'Beyond the Event Horizon: The Movie',
    japaneseTitle: '事件の地平線を超えて',
    synopsis: 'The theatrical spectacle following the voyage across warp anomalies to rescue a forgotten colony ship at the edge of the galaxy.',
    posterImage: IMAGES.moviePoster,
    bannerImage: IMAGES.movieBanner,
    rating: 9.4,
    scoreCount: 310000,
    rank: 2,
    popularity: 420000,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    releasedYear: 2023,
    season: 'Summer',
    studio: 'Aetherial Works',
    genres: ['Sci-Fi', 'Drama', 'Movie'],
    featured: true,
    trending: false,
    popular: true,
    latest: false,
    episodes: generateEpisodes(1, 'Horizon Movie'),
  },
  {
    id: '6',
    slug: 'phantom-protocol-shinjuku',
    title: 'Phantom Protocol: Shinjuku 2099',
    japaneseTitle: 'ファントムプロトコル',
    synopsis: 'An underground cyber-detective agency battles rogue AI synthetics hiding among human society, navigating conspiracy networks in deep neon alleyways.',
    posterImage: IMAGES.cyberpunkPoster,
    bannerImage: IMAGES.cyberpunkBanner,
    rating: 8.5,
    scoreCount: 64200,
    rank: 22,
    popularity: 110000,
    format: 'TV',
    status: 'Ongoing',
    episodesCount: 12,
    releasedYear: 2024,
    season: 'Summer',
    studio: 'Kurogane Animation',
    genres: ['Cyberpunk', 'Mystery', 'Action'],
    featured: false,
    trending: true,
    popular: false,
    latest: true,
    episodes: generateEpisodes(12, 'Phantom Protocol'),
  },
  {
    id: '7',
    slug: 'celestial-gardens-ova',
    title: 'Celestial Gardens & The Whispering Winds',
    japaneseTitle: '天界の庭園',
    synopsis: 'A tranquil OVA exploring the peaceful daily life of guardian spirits maintaining the floral biomes of the heavens.',
    posterImage: IMAGES.fantasyPoster,
    bannerImage: IMAGES.fantasyBanner,
    rating: 8.3,
    scoreCount: 28400,
    rank: 45,
    popularity: 58000,
    format: 'OVA',
    status: 'Completed',
    episodesCount: 3,
    releasedYear: 2022,
    season: 'Spring',
    studio: 'Kyoto Wave',
    genres: ['Slice of Life', 'Fantasy', 'Comedy'],
    featured: false,
    trending: false,
    popular: false,
    latest: false,
    episodes: generateEpisodes(3, 'Celestial Gardens'),
  },
  {
    id: '8',
    slug: 'solar-odyssey',
    title: 'Solar Odyssey: Path to Sol',
    japaneseTitle: 'ソーラーオデッセイ',
    synopsis: 'A crew of interstellar explorers charts uncharted wormholes to find a mythical solar realm said to harbor infinite energy.',
    posterImage: IMAGES.spacePoster,
    bannerImage: IMAGES.spaceBanner,
    rating: 8.9,
    scoreCount: 175000,
    rank: 6,
    popularity: 260000,
    format: 'TV',
    status: 'Ongoing',
    episodesCount: 24,
    releasedYear: 2024,
    season: 'Winter',
    studio: 'Nexus Vision',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    featured: false,
    trending: true,
    popular: true,
    latest: true,
    episodes: generateEpisodes(24, 'Solar Odyssey'),
  },
];

export const MOCK_USER: UserProfile = {
  name: 'Alex Vance',
  username: 'vance_otaku',
  email: 'alex.vance@aetheranime.io',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
  banner: IMAGES.cyberpunkBanner,
  joinedDate: 'January 2024',
  episodesWatched: 482,
  hoursWatched: 194,
  favoriteGenre: 'Cyberpunk & Sci-Fi',
  level: 42,
  xp: 8450,
};

export const MOCK_HISTORY: WatchHistoryItem[] = [
  {
    anime: MOCK_ANIME[0],
    episode: MOCK_ANIME[0].episodes[3],
    watchedAt: '10 minutes ago',
    progressSeconds: 840,
    durationSeconds: 1455,
  },
  {
    anime: MOCK_ANIME[1],
    episode: MOCK_ANIME[1].episodes[1],
    watchedAt: 'Yesterday',
    progressSeconds: 1455,
    durationSeconds: 1455,
  },
  {
    anime: MOCK_ANIME[2],
    episode: MOCK_ANIME[2].episodes[11],
    watchedAt: '3 days ago',
    progressSeconds: 1120,
    durationSeconds: 1455,
  },
];
